name: scenarioshelf
description: TRPG通過シナリオ保存サービス
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Design
  cupertino_icons: ^1.0.2

  # Firebase
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  cloud_firestore: ^4.8.3

  # State management
  flutter_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  freezed_annotation: ^2.2.0

  # Transition
  go_router: ^9.0.1

  # Other
  intl: ^0.18.1
  logger: ^1.4.0
  google_sign_in: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Generator
  build_runner: ^2.4.6
  riverpod_generator: ^2.2.3
  freezed: ^2.3.5
  flutter_launcher_icons: ^0.13.1

  # Linter
  very_good_analysis: ^5.0.0+1
  custom_lint: ^0.4.0
  riverpod_lint: ^1.3.2

  # build_runner の実行コマンド
  # fvm flutter packages pub run build_runner build --delete-conflicting-outputs

flutter:
  uses-material-design: true
  fonts:
    - family: IBMPlexSansJP
      fonts:
        - asset: assets/fonts/IBMPlexSansJP-Thin.ttf
          weight: 100
        - asset: assets/fonts/IBMPlexSansJP-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/IBMPlexSansJP-Light.ttf
          weight: 300
        - asset: assets/fonts/IBMPlexSansJP-Regular.ttf
          weight: 400
        - asset: assets/fonts/IBMPlexSansJP-Medium.ttf
          weight: 500
        - asset: assets/fonts/IBMPlexSansJP-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/IBMPlexSansJP-Bold.ttf
          weight: 700
  assets:
    - assets/images/logo/
